server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pazienti_db?useSSL=false&serverTimezone=UTC
    username: root
    password: a7a1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
